enum CategoryType {
    RECEIPT
    FIXED
    VARIABLE
    PERSON
    PAYMENT_ENTITY
}

type Query {
    category(id: ID!): Category!
    categories(
        startDate: Date
        endDate: Date
        categoryType: CategoryType
        currentPag: Int!
        limit: Int!
    ): CategoryPayload!
}

type Mutation {
    createCategory(data: createCategoryInput): Category!
    updateCategory(id: ID!, data: updateCategoryInput): Category!
    deleteCategory(id: ID!): Category!
    deleteManyCategory(ids: [ID!]!): CategoryPayload!
}

type Category {
    id: ID!
    name: String!
    categoryType: CategoryType!
    createdAt: Date!
    creator: User!
}

type CategoryPayload {
    nodes: [Category!]!
    total: Int!
}

input createCategoryInput {
    name: String!
    categoryType: CategoryType!
}

input updateCategoryInput {
    name: String
    categoryType: CategoryType
}