scalar Date

enum CategoryType {
    RECEIPT
    FIXED
    VARIABLE
    PERSON
    PAYMENT_ENTITY
}

enum MutationType {
    CREATED
    DELETED
    UPDATED
}

enum ReceiptType {
    RECEIPT
    FIXED
    VARIABLE
    PERSON
}

enum IsReceiptPaid { 
    YES 
    NO 
}